branches:
  only:
  - develop
language: java
jdk:
- openjdk11
before_install:
- cd frontend
- openssl aes-256-cbc -K $encrypted_4931efa05e37_key -iv $encrypted_4931efa05e37_iv
  -in env.tar.enc -out env.tar -d
- tar xvf env.tar
- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
- ". ~/.nvm/nvm.sh"
- nvm install node
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- cd .. && cd backend
- chmod +x gradlew
before_script:
- cd .. && cd frontend
- npm install
script:
- npm run build:dev
- cd .. && cd backend
- "./gradlew clean build"
- cd ..
before_deploy:
- mkdir -p before-deploy
- cp scripts/*.sh before-deploy/
- cp appspec.yml before-deploy/
- cp backend/build/libs/*.jar before-deploy/
- cp -r frontend/build before-deploy/build
- cd before-deploy && zip -r before-deploy *
- cd ../ && mkdir -p deploy
- mv before-deploy/before-deploy.zip deploy/project-jikji.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: project-jikji-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    branch: develop
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: project-jikji-build
  key: project-jikji.zip
  bundle_type: zip
  application: project-jikji
  deployment_group: project-jikji-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    branch: develop
notifications:
  slack:
    secure: R2JDrNxTqNl4HLaD0PCKsUBuFM3d9Uc6kA+QKWKljrBVwSNQygur+yZvvQonj9qx7lK4ghikkRtzbsc/CAuap7zNzI/GR9s47vUWk7Az+xPO1YGWcAg0B/7L/qJBiSoB7Y/eMBOrWVc0qr+YoT7XwFoH6GHWlFz+7sIJrZOXAOM6akMO+k+oHB0Qvr6K83p9MVOApOSf5RdlTa5AFu7tSm9sFCHJdRg6BQ7Y5/IHKN3BDCf53avoweCdSISYYVtOfHHQrVdwVIMqgAhv+4EgtzLRVXSPldU/FqdT5JiiRrXCBkGRGcq9RFmxJIpf0VoJXJmlOXN1qhY+kTqtPaHxM3YRZpAIVu9kQm2FuxC1NNEtaOjmudyydBPXPFIVpS3ItCuav0uTsomKd78BQ/6QqKv5wCSkoUc7tYd02JU7WGOeG4GUGxdDXqZV8mwEBo5hDo+bygFsaOuFVTO9tGBmZ0tyolSfisR0+y8e7KYAIViPW5jw6nESirfdutx9I05MvUPdZRT9g/lvjnI9LQwQtWXJe8BPzohGkW1R3MW7usgP0TW3mMfLFix215dZqclYvAhas29V4DGkc+NKbK0MaN74yjz+MqGDH1BAtEFG6ttN1H6dMpnpZtJ7cbSFiFg9vP5/8vt1uN9/xAC2m3y+Ecs4dUaXdtut2YQCm0i+4wg=
  email: false
