branches:
  only: 
    - develop

stages:
  - frontend
  - backend

jobs:
  include:
  - stage: frontend
    branches:
      only: 
        - develop
    language: node_js
    node_js: 14
    cache: npm
    before_script:
      - cd frontend
      - npm install
    script: 
      - npm run build:dev
      - rm -rf node_modules
      - cd ..
  - stage: backend
    branches:
      only: 
        - develop
    language: 
      - java
      - node_js
    jdk: openjdk11
    node_js: 14
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
    install:
      - chmod +x gradlew
    script: 
      - ./gradlew clean build
    before_deploy:
    - mkdir -p before-deploy
    - cp scripts/*.sh before-deploy/
    - cp appspec.yml before-deploy/
    - cp build/libs/*.jar before-deploy/
    - cp -r frontend before-deploy/
    - cd before-deploy && zip -r before-deploy *
    - cd ../ && mkdir -p deploy
    - mv before-deploy/before-deploy.zip deploy/project-jikji.zip
    deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: project-jikji-build
      region: ap-northeast-2
      skip_cleanup: true
      acl: private
      local_dir: deploy
      wait-until-deployed: true
      on: 
        branch: develop
    - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: project-jikji-build
      key: project-jikji.zip
      bundle_type: zip
      application: project-jikji
      deployment_group: project-jikji-group
      region: ap-northeast-2
      wait-until-deployed: true
      on: 
        branch: develop

notifications:
  slack:
    secure: R2JDrNxTqNl4HLaD0PCKsUBuFM3d9Uc6kA+QKWKljrBVwSNQygur+yZvvQonj9qx7lK4ghikkRtzbsc/CAuap7zNzI/GR9s47vUWk7Az+xPO1YGWcAg0B/7L/qJBiSoB7Y/eMBOrWVc0qr+YoT7XwFoH6GHWlFz+7sIJrZOXAOM6akMO+k+oHB0Qvr6K83p9MVOApOSf5RdlTa5AFu7tSm9sFCHJdRg6BQ7Y5/IHKN3BDCf53avoweCdSISYYVtOfHHQrVdwVIMqgAhv+4EgtzLRVXSPldU/FqdT5JiiRrXCBkGRGcq9RFmxJIpf0VoJXJmlOXN1qhY+kTqtPaHxM3YRZpAIVu9kQm2FuxC1NNEtaOjmudyydBPXPFIVpS3ItCuav0uTsomKd78BQ/6QqKv5wCSkoUc7tYd02JU7WGOeG4GUGxdDXqZV8mwEBo5hDo+bygFsaOuFVTO9tGBmZ0tyolSfisR0+y8e7KYAIViPW5jw6nESirfdutx9I05MvUPdZRT9g/lvjnI9LQwQtWXJe8BPzohGkW1R3MW7usgP0TW3mMfLFix215dZqclYvAhas29V4DGkc+NKbK0MaN74yjz+MqGDH1BAtEFG6ttN1H6dMpnpZtJ7cbSFiFg9vP5/8vt1uN9/xAC2m3y+Ecs4dUaXdtut2YQCm0i+4wg=
  email: false