branches:
  only:
  - develop
  - main
os:
- linux
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_4931efa05e37_key -iv $encrypted_4931efa05e37_iv
  -in env.tar.enc -out env.tar -d
- openssl aes-256-cbc -K $encrypted_15e4a6eb5ffe_key -iv $encrypted_15e4a6eb5ffe_iv
  -in resources-profiles.tar.enc -out resources-profiles.tar -d
- tar xvf env.tar -C frontend/
- tar xvf resources-profiles.tar -C backend/src/main/
- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
- ". ~/.nvm/nvm.sh"
- nvm install node
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- cd backend
- chmod +x gradlew
before_script:
- cd .. && cd frontend
- npm install
script:
- if [ "$TRAVIS_BRANCH" = "develop" ]; then npm run build:dev; fi
- if [ "$TRAVIS_BRANCH" = "main" ]; then npm run build:prod; fi
- cd .. && cd backend
- "./gradlew clean build"
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cd ..; fi
before_deploy:
- if [ "$TRAVIS_BRANCH" = "develop" ]; then mkdir -p before-deploy; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cp scripts/*.sh before-deploy/; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cp appspec.yml before-deploy/; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cp backend/build/libs/*.jar before-deploy/; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cp -r frontend/build before-deploy/build; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cd before-deploy && zip -r before-deploy *; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then cd ../ && mkdir -p deploy; fi
- if [ "$TRAVIS_BRANCH" = "develop" ]; then mv before-deploy/before-deploy.zip deploy/project-jikji.zip; fi
deploy:
  matrix:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: project-jikji-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: develop
  - provider: codedeploy
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: project-jikji-build
    key: project-jikji.zip
    bundle_type: zip
    application: project-jikji
    deployment_group: project-jikji-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: develop
  - provider: netlify
    site: "$NETLIFY_SITE_ID"
    auth: "$NETLIFY_AUTH_TOKEN"
    dir: "../frontend/build/"
    edge: true
    prod: true
    on:
      branch: main
  - provider: heroku
    api_key:
      secure: 5zHPkSP9zmFboU6JYJY75f0UbMuVRW8wFR+SleFY/rm2mNK84Y5yVY9P1F5SYWMRDOS1YO+o9TsRzAvi9VILe1i0z/WNmapYiwTZEPswR1K9o8icIxeo+nrBnj/vj+nBGOTh6/FqRSZmv2KCpQJySwB6kXXrrdIGQBlT6oMF8LxKMwCeiJMW6MXH3UjfMb8POZWxDf+tFGbQdR3mP+OY2ZUCvZNS6sezM5oI0aNzKghkkp+BX9aGzR4ntNkSdp5PDm5rYR17JKX+1ybEVM8vNyv1jFnRusw2b/cfOPfJUFnnzAnEWTOyzeWUzo+G27qEYZij8GUbtUMAU28UfrwlERLrUzz9cOOaWS3EsxDkeMru4slGqvSeocOn5qYYdGk4m2SH4n/WGGwx2Ww/w4Cz8ndxFTzO0TpBEEf7n3WkFdzOn4NCvYW0fK+GLDLj5otE9Wnq+Fp+OoMkzmk9AxuB8fBGwpeDCDyXIWsPz5/Vz4yHJ3lfHVX8yqU93sPM51LBYkhMDmCtGVQfiAJLCrT658moOA9j0LcS+ljGKzyLsfVWiOJNjF4wYNRPr05nWXL94kLh5i6eALAu7NoE7d3KnigLvfUxs+wEgCid5JQqLuse0y4GLeYW8cv9DdD/QnkUEFsW4vilMxPz7ZJRoG0gkuWFIF/Gsyo1DGO0qRnI1Vo=
    skip_cleanup: true
    app: project-jikji-api
    on:
      branch: main
notifications:
  slack:
    secure: R2JDrNxTqNl4HLaD0PCKsUBuFM3d9Uc6kA+QKWKljrBVwSNQygur+yZvvQonj9qx7lK4ghikkRtzbsc/CAuap7zNzI/GR9s47vUWk7Az+xPO1YGWcAg0B/7L/qJBiSoB7Y/eMBOrWVc0qr+YoT7XwFoH6GHWlFz+7sIJrZOXAOM6akMO+k+oHB0Qvr6K83p9MVOApOSf5RdlTa5AFu7tSm9sFCHJdRg6BQ7Y5/IHKN3BDCf53avoweCdSISYYVtOfHHQrVdwVIMqgAhv+4EgtzLRVXSPldU/FqdT5JiiRrXCBkGRGcq9RFmxJIpf0VoJXJmlOXN1qhY+kTqtPaHxM3YRZpAIVu9kQm2FuxC1NNEtaOjmudyydBPXPFIVpS3ItCuav0uTsomKd78BQ/6QqKv5wCSkoUc7tYd02JU7WGOeG4GUGxdDXqZV8mwEBo5hDo+bygFsaOuFVTO9tGBmZ0tyolSfisR0+y8e7KYAIViPW5jw6nESirfdutx9I05MvUPdZRT9g/lvjnI9LQwQtWXJe8BPzohGkW1R3MW7usgP0TW3mMfLFix215dZqclYvAhas29V4DGkc+NKbK0MaN74yjz+MqGDH1BAtEFG6ttN1H6dMpnpZtJ7cbSFiFg9vP5/8vt1uN9/xAC2m3y+Ecs4dUaXdtut2YQCm0i+4wg=
  email: false