branches:
  only: 
    - main
    - develop

stages:
  - name: main
    if: branch = main
  - name: develop
    if: branch = develop

matrix:
  include:
  - stage: develop
  - language: java
    jdk: openjdk11
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
    install:
      - chmod +x gradlew
    script: 
      - ./gradlew clean build
  - language: node_js
    node_js: 14
    cache: npm
    before_script:
      - cd frontend
      - npm install
    script: 
      - npm run build

notifications:
  slack: $SLACK_NOTIFICATION
  email: false