spring:
  profiles:
    group:
      local:
        - local
        - local-common
        - common
      dev:
        - dev
        - dev-common
        - common
      prod:
        - prod
        - prod-common
        - common